variables:
  DOCKER_DRIVER: overlay
  GCP_PROJECT_ID: dhg-data-intelligence-ops
  PROJECT_KEY: di-dataops:obi
  PROJECT_NAME: obi

stages:
  - coding-styles-analysis
  - code-quality-analysis

golint-analysis:
  stage: coding-styles-analysis
  image: eu.gcr.io/dhg-data-intelligence-ops/golint:alpine-3.7
  script:
  - chmod +x golint-checker.sh && ./golint-checker.sh .

sonar-analysis:
  stage: code-quality-analysis
  image: eu.gcr.io/$GCP_PROJECT_ID/sonar-scanner:alpine-3.6
  script:
  - /sonar-scanner/bin/sonar-scanner -Dsonar.host.url=http://sonar-sonarqube:9000 -Dsonar.projectKey=${PROJECT_KEY} -Dsonar.projectName=${PROJECT_NAME} -Dsonar.sources=. -Dsonar.login=${SONAR_LOGIN}
