apiVersion: apps/v1
kind: Deployment
metadata:
  name: obi-master
  namespace: obi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obi-main
  template:
    metadata:
      labels:
        app: obi-main
    spec:
      containers:
      - name: obi-latest
        image: eu.gcr.io/dhg-data-intelligence-ops/obi
        volumeMounts:
        - name: obi-dataproc-sa-volume
          mountPath: "/etc/sa"
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: "dhg-data-intelligence-ops"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/sa/dataproc-sa.json"
      volumes:
        - name: obi-dataproc-sa-volume
          secret:
            secretName: dataproc-sa
---
apiVersion: v1
kind: Service
metadata:
  name: obi-service
  namespace: obi
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: UDP
  selector:
    app: obi-main