apiVersion: v1
kind: ConfigMap
metadata:
  namespace: obi
  name: master-config
data:
  # This file is used to demonstrate how to attach a Dataproc infrastructure
  # to OBI. All the configuration fields specified in this field are strictly
  # required unless specified.

  # Optional. The name of the infrastructure
  name: dataproc

  # Optional. Namespace used to identify deployment objects in certain platforms
  # e.g. Kubernetes. It is not required if the deployment type is local. If the
  # deployment type is Kubernetes and the namespace is not specified, the
  # namespace 'obi' will be used
  namespace: obi

  # This is the service account file path for which the client will
  # create a secret to be attached to the infrastructure deployment
  dataprocServiceAccountPath: /Users/l.lombardo/Documents/dataproc-sa.json

  # This is the service account file path for which the client will
  # create a secret to be attached to the infrastructure deployment
  # to be used when it needs GCS permissions
  gcsServiceAccountPath: /Users/l.lombardo/Documents/gcs-service-account.json

  # Google Cloud's project ID under which the Dataproc instance is registered
  projectId: dhg-data-intelligence-ops

  # Region for the Dataproc servers to be used
  region: global

  # Zone for the Dataproc servers to be used
  zone: europe-west3-b

  schedulingLevels: /
    level0.timeout=180
    level0.policy=0
    level0.binCapacity=3600
    level1.timeout=300
    level1.policy=1
    level1.binCapacity=3

  priorityMap: /
    csv_update=2
    csv_find=2

  # Those variables are used to tell OBI where to find a persistent
  # database to be used to provide high availability. This feature
  # can also be disabled by simply not specifying dbType parameter
  dbType: postgres
  dbHost: 10.51.242.136
  dbPort: "5432"
  dbUser: stolon
  dbPassword: chDW8biDvA0lVl0zbBpVwunGS9zdqgctqzHpryhb
  dbName: obi