kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-heartbeat
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - protocol: UDP
    port: 8080
    targetPort: 8080
    nodePort: {{ .Values.freeNodePort }}
  selector:
    app: {{ .Release.Name }}-master
  type: NodePort

